In [20]:
import pandas as pd

"""
------------ WRITE ZIP FILES -----------
"""
# Read data from internet
url = "https://raw.githubusercontent.com/keitazoumana/Fastapi-tutorial/master/data/spam.csv"
spam_data = pd.read_csv(url, encoding="ISO-8859-1")
display(spam_data)
# Save it as a .csv file
spam_data.to_csv("spam.csv")
# Save it as a zip file
spam_data.to_csv("spam.csv.zip", compression="zip")

# Check the files sizes
from os import path
print("Compressing ratio(perc): ", 100 * path.getsize('spam.csv.zip') /  path.getsize('spam.csv'))


"""
------------ READ ZIP FILES -----------
"""
# Case 1: read a single zip file 
spam_df_unzip = pd.read_csv('spam.csv.zip', compression='zip')

# Case 2: read a file from a folder
from zipfile import ZipFile

# Read the file from a zip folder
spam_df = pd.read_csv(ZipFile("spam.csv.zip").open('spam.csv'))
display(spam_df)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

Compressing ratio(perc):  43.10390383083717

,Unnamed: 0,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...,...
5567,5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,5571,ham,Rofl. Its true to its name,NaN,NaN,NaN