In [3]:
import pandas as pd
import numpy as np

In [5]:
# contains random values:

df1=pd.util.testing.makeDataFrame()
df1

                   A         B         C         D
5keLwIXO0t -0.551605  0.133305 -0.716312 -0.714905
gBSTOL8dM0 -1.413812 -1.102982 -0.652023  1.036938
PZkv8o2TZr -0.690017 -1.266041  0.400029  0.426709
4yQ1fqaOHI -0.236431  0.327101  0.573505  2.032672
lNsp4CMcD5 -0.414843  2.113610  0.616946 -0.039105
LIHs962PTj -0.925707  1.036062  0.752386 -0.514513
5aNfoYVMyq -1.744509 -0.872578  2.655409  1.804568
b6pKFts8C5  0.656239  0.411886  0.505868 -0.228517
JioZJjGxS9  0.145418  1.234016  1.420680 -1.127125
paubQ61Ixv  2.250007 -0.904663 -0.217612 -0.205072
0eJag2C0IV -0.134006 -0.162133  0.488525  1.460857
a5VInBDoI1  0.167706  0.126451 -1.570718 -1.215436
sIAPxNAN1v -1.501074 -1.150822 -0.033415 -1.362624
JVP6TTaOIw  1.230722 -0.817812 -0.717161 -0.587823
hnhg5KLLS0  1.162668 -0.923117 -1.288224 -2.328994
1o2XgHZUk8  0.211251 -0.630244 -0.106749 -1.272536
qK8hR4eQ93  1.233687 -0.376590 -1.644721 -0.257985
mh89eUWrMd -0.929502  0.763581 -0.160631 -0.200568
NTRL8XMGlA -0.249271 -1.152284 -0.997340  0.850325
d5hBMjp2QK -1.515128 -0.443095  0.807629  0.115660
pLOuiDGFhP -0.970672  0.117129 -0.725066  0.426005
i9bIdrPYcl  0.190301 -0.793390 -0.245281  0.368120
4aiD755UfW  0.282490  1.843718  1.199368 -2.762389
AnfOBpanXt -1.627937  1.281257 -0.745924  1.082273
X9MAZoTxW1 -0.559001 -0.342601  0.153315  0.800976
QFRnMDDgBs  0.254109  0.542668  0.877398 -1.864647
iI82dmWIvu  0.532322  0.065863 -0.201227 -0.531221
rpkIqsAnlc  0.128011 -0.974161  1.432612  1.541973
sSBltZ6Qkw  1.184332  1.300113  0.105282 -0.364106
ujmwNRmyF4 -1.113756  1.043020 -2.105801  0.614855

In [8]:
# contains missing values:

df2=pd.util.testing.makeMissingDataframe()
df2

                   A         B         C         D
ZnnFLeQ5SA       NaN  2.329527  0.946619       NaN
rDZjwTvsRT  0.085789 -0.539149 -2.536338 -0.044017
Rw180DyvP5 -0.774729 -1.453517 -0.694004 -0.494740
RkX3GuOrBH -0.533672 -1.708738 -1.072023  2.691244
2GxiCeH1o3 -1.895485 -0.414282  0.298467  1.351287
UPwpWFEMxE  0.115705  0.567917       NaN -0.037638
tkP5DMgas9  0.612296  1.623591  1.519136 -0.028290
CHBZIv8vLQ -0.109291 -1.030933       NaN -0.365182
siaEF1XrxS -2.096799 -0.289247 -0.644747  0.014163
0UEfMHjX9C  0.025981 -0.253053 -0.186047 -0.406873
8H8kkhZQVs       NaN -0.040725  1.046995 -0.786903
BDJaVyu8r8  0.537893       NaN -0.633463 -0.193855
dYHVk3QMjQ -1.092546  1.127387  0.344237       NaN
DAoRxpFqUa  0.039059  0.001656  0.347576 -1.014433
o68YIMZWwh  0.302326  0.814685 -2.302752  1.374243
sx0Lm8UZeD       NaN  0.851714  0.768585 -0.323171
w9cWKogvb6       NaN -0.531925  0.737967 -0.445563
ZkVsxxKicR  0.513808  1.405769       NaN  1.298277
1UHGzZTwzH       NaN -0.316305 -1.134346  1.651490
jS8CD5V5aV -0.738453  1.077838 -1.327058 -0.161353
x3eBLvXtjh  0.348341 -1.814949  0.146055 -0.682286
Aa3Bzi6hTQ  1.020399 -0.013424  1.413897 -0.213423
73sJnmoV2G  0.042104       NaN -0.216118 -1.244889
lsCAco4phh  0.230657  0.762998  0.052195  0.293075
x95v1itEHd  0.055657 -0.335186  0.630580  0.137110
o5Vbi7QBjg  2.445925 -0.797229  0.318525  0.989335
QpWfE715Wr -2.544321 -0.154711  0.470975  1.049731
KGBDv81u9Z  0.998354  0.443924  0.847041  0.952473
79FZMb4teo  0.716954  1.043082 -0.661108 -0.500286
H3Jwgs30fw -0.129693  0.232644  1.277251 -0.142719

In [9]:
# contains datetime values:

df3=pd.util.testing.makeTimeDataFrame()
df3

                   A         B         C         D
2000-01-03  0.287769  0.447443 -1.169640  1.003015
2000-01-04  0.393531  0.077297  0.064755 -0.515075
2000-01-05 -0.717168 -1.530122  1.077283 -1.449969
2000-01-06 -0.896827  2.030681  2.867373 -0.172822
2000-01-07  0.585895 -0.654246  1.062635 -1.877972
2000-01-10  0.085136  1.627228  0.497770 -0.441012
2000-01-11 -1.049122  1.410937 -0.751349  1.056158
2000-01-12  1.658856  0.159525  0.106274  2.259146
2000-01-13 -0.147912  2.629611  0.391398 -0.304737
2000-01-14 -0.532140  0.224982  1.463823  0.339184
2000-01-17  0.163302  1.150707 -1.311100  0.461106
2000-01-18 -0.137548 -0.351470  1.465331  1.135752
2000-01-19  0.719866 -0.298140 -1.368084  1.458070
2000-01-20 -0.718393  0.151759  1.275808  0.312559
2000-01-21  0.711780  0.968242  1.265461  1.939875
2000-01-24  0.176794 -0.157573 -0.021534 -0.008846
2000-01-25 -0.264385 -0.190882  0.560732 -0.935805
2000-01-26 -0.078499  0.567639 -1.099802 -0.284923
2000-01-27  0.672849 -1.495383  0.077739 -0.916628
2000-01-28 -0.450489  1.427516 -1.438573  0.829931
2000-01-31 -0.104187 -1.693480 -0.983025  1.548174
2000-02-01  0.482194 -0.135277 -0.044200  1.079318
2000-02-02  0.319443  0.057617  0.744764 -1.137717
2000-02-03 -0.084909 -1.113847 -0.879022 -0.233875
2000-02-04 -0.275696  0.093785  0.783039  1.144941
2000-02-07  1.210771  2.404449  0.707399  0.199540
2000-02-08 -0.176717 -0.980979  0.214955  0.214468
2000-02-09 -0.738020 -0.015931  0.434921 -1.713873
2000-02-10  0.270921  0.039897  1.243612 -0.886577
2000-02-11 -0.077914 -0.662047  0.964534 -1.213445

In [11]:
# contains mixed values:

df4=pd.util.testing.makeMixedDataFrame()
df4

     A    B     C          D
0  0.0  0.0  foo1 2009-01-01
1  1.0  1.0  foo2 2009-01-02
2  2.0  0.0  foo3 2009-01-05
3  3.0  1.0  foo4 2009-01-06
4  4.0  0.0  foo5 2009-01-07